from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass(frozen=True)
class JobPreferences:
    """User-stated job search preferences recorded across runs."""

    focus_highlights: tuple[str, ...] = ()
    target_roles: tuple[str, ...] = ()
    preferred_locations: tuple[str, ...] = ()
    remote: bool | None = None
    job_types: tuple[str, ...] = ()
    company_stages: tuple[str, ...] = ()
    industries: tuple[str, ...] = ()
    min_salary: int | None = None
    visa_sponsorship: bool | None = None
    sources: tuple[str, ...] = ()
    excluded_terms: tuple[str, ...] = ()
    result_count: int | None = None
    output_format: str | None = None
    notes: str | None = None


@dataclass(frozen=True)
class UserProfile:
    """Structured representation distilled from candidate-provided material."""

    raw_text: str
    name: str | None = None
    headline: str | None = None
    roles: tuple[str, ...] = ()
    skills: tuple[str, ...] = ()
    locations: tuple[str, ...] = ()
    links: tuple[str, ...] = ()
    seniority: str | None = None
    keywords: tuple[str, ...] = ()
    preferences: JobPreferences = field(default_factory=JobPreferences)
    evidence: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class SearchQuery:
    """A query generated by the search agent for one or more job platforms."""

    text: str
    role: str | None = None
    skills: tuple[str, ...] = ()
    location: str | None = None
    remote: bool | None = None


@dataclass(frozen=True)
class JobPosting:
    """Normalized job record returned by a platform adapter."""

    source: str
    source_id: str
    title: str
    company: str
    url: str
    location: str | None = None
    description: str = ""
    tags: tuple[str, ...] = ()
    salary: str | None = None
    posted_at: datetime | None = None
    raw: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class JobMatch:
    """A ranked job plus explainable score details."""

    job: JobPosting
    score: float
    matched_terms: tuple[str, ...] = ()
    query: SearchQuery | None = None
    rationale: str = ""
